# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_about_brand_catalogue_certificate_contact_cooperation_map_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
