# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20160204_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='text',
            field=models.CharField(default='type', max_length=600),
        ),
        migrations.AddField(
            model_name='certificate',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='text',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
