# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20160204_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='text',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
