# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20160204_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='type', max_length=600),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
