# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20160204_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='address',
            field=models.CharField(default='type', max_length=600),
        ),
        migrations.AddField(
            model_name='map',
            name='desc',
            field=models.CharField(default='type', max_length=600),
        ),
        migrations.AddField(
            model_name='map',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='map',
            name='phone',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
