# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_menu_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='price',
            field=models.CharField(default='type', max_length=600),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='text',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
