# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20160204_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='paragraph',
            field=models.CharField(default='type', max_length=600),
        ),
    ]
