# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_cooperation_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='paragraph',
        ),
    ]
