# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20160205_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='paragraph',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='cooperation',
            name='title',
        ),
    ]
