# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0012_auto_20160205_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='paragraph',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
