# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20160205_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='description',
            field=models.TextField(default='type', max_length=600),
        ),
    ]
