# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0015_auto_20160205_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
