# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0016_auto_20160205_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
