# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0017_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
