# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0018_contact_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='paragraph',
            field=models.TextField(default='type', max_length=600),
        ),
    ]
